// Generated by CoffeeScript 1.3.3
(function() {
  var PASS_NAME;

  PASS_NAME = 'compileFromCoffeeScript';

  module.exports = {
    initialize: function(PEG) {
      var appliedPassNames, index;
      PEG.compiler.passes[PASS_NAME] = this.pass;
      appliedPassNames = PEG.compiler.appliedPassNames;
      if (appliedPassNames.indexOf(PASS_NAME) === -1) {
        index = appliedPassNames.indexOf('allocateRegister');
        return appliedPassNames.splice(index - 1, 0, PASS_NAME);
      }
    },
    pass: function(ast) {
      return console.log("I was called");
    }
  };

}).call(this);
