// Generated by CoffeeScript 1.3.3
(function() {
  var utils;

  utils = {
    buildNodeVisitor: function(functions) {
      return function(node) {
        return functions[node.type].apply(null, arguments);
      };
    }
  };

  module.exports = utils;

}).call(this);
